### ISSUE TITLE
Wrong country for OSL

### ISSUE THREAD

**Issue by joleeee** [aashishvanand/airport-data-js#8]
Hey, just tried this and the first airport i tried returned wrong data

<img width="239" alt="image" src="https://github.com/aashishvanand/airport-data-js/assets/24441708/72a18eb7-c0ed-4f58-9584-041244688d42">

OSL is in NO, but NO is Norway, not Nannestad. Nannestad is a municipality which contains Teigebyen, which is a village of 3k people.

A similar thing for CPH which is in Denmark...
<img width="265" alt="image" src="https://github.com/aashishvanand/airport-data-js/assets/24441708/5dddaedb-09af-4c4c-97c9-f5132c282d50">

**Comment by joleeee** [comment]
Even the example on the front page has the wrong country...

![image](https://github.com/aashishvanand/airport-data-js/assets/24441708/d22fc5bc-35f4-4e18-b33a-ef977c76d360)

**Comment by joleeee** [comment]
I am also wondering about this, there are two iata codes (OSL, GEN) for icao ENGM, both go to Oslo Gardermoen, but they have slightly different coordinates in this db, and GEN is missing a lot of links. The links are there but they either dont work or redirect to OSL. I think GEN is historical? Not sure if this is expected.


![image](https://github.com/aashishvanand/airport-data-js/assets/24441708/9dc1cbe3-311d-447c-aa96-99966b70401c)

<img width="448" alt="image" src="https://github.com/aashishvanand/airport-data-js/assets/24441708/5af1d903-095b-411c-9992-308b4de3d548">

**Comment by aashishvanand** [comment]
Hi @joleeee,

Thank you for pointing out these inaccuracies with the airport data, including the issues with OSL, CPH, and the IATA codes for ENGM. I appreciate your detailed feedback and the examples you've provided.

Yes, I will address and fix these issues in the next update.

**Comment by aashishvanand** [comment]
@joleeee There is a difference between "Country" and "County" and "City"

I have anyways found another source that has updated City. Will be releasing it soon.

Regarding GEN. I will check if I can remove such records.
